name: Backend Continuous Integration

on: 
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:      

  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.10"
  
      - name: Install dependencies
        working-directory: starter/backend 
        run:  |
          python -m pip install --upgrade pip
          pip install flake8
          pip install pipenv

      - name: Run lint
        working-directory: starter/backend
        run: pipenv run flake8 .

  Test:
    runs-on: ubuntu-latest
    needs: Linting

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        working-directory: starter/backend 
        run:  |
          python -m pip install --upgrade pip
          pip install pipenv
          pip install pytest

      - name: Run tests
        working-directory: starter/backend
        run: pipenv run pytest

  Build:
    runs-on: ubuntu-latest
    needs: [Linting, Test]
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Build Docker Image
        working-directory: starter/backend
        run: |
          docker build --tag mp-backend:latest .
